### ISSUE TITLE
Bugs that may affect vision

### ISSUE THREAD

**Issue by Sibei46** [KaguyaStudio-MC/NeOculus#8]
### What happened?

Sorry, I used machine translation to report a bug. I just found a bug that may affect the viewing experience. When using 1.21-neoforge's neoculus, the lava will be overexposed, while when using 1.20.1-fabric's iris, it will not be.

### Screenshots

![Image](https://github.com/user-attachments/assets/91bb1be6-d65a-4aa3-baad-034539444445)
![Image](https://github.com/user-attachments/assets/4312f565-db94-4f92-847b-0cc9a08ef84a)
[issue-cn.txt](https://github.com/user-attachments/files/19220664/issue-cn.txt)
[1.21.1-NeoForge_21.1.133.zip](https://github.com/user-attachments/files/19220668/1.21.1-NeoForge_21.1.133.zip)

### Log output

[neo_log.log](https://github.com/user-attachments/files/19220721/neo_log.log)

### Minecraft Version

Minecraft 1.21.1

### Iris Version

neoculus-mc1.21.1-1.8.2

### Operating System

windows 11

### What is your GPU?

Nvidia GeForce GTX 1650

**Comment by Sibei46** [comment]
Ok, let me provide some more information. [1.21.1-NeoForge_21.1.133.zip](https://github.com/user-attachments/files/19220668/1.21.1-NeoForge_21.1.133.zip) is the mrpack+launcher package at the beginning, not the mc source file (I'm just a little perfunctory). Secondly, the light and shadow I used is Complementary Shaders - Unbound. The way to reproduce is to open the light and shadow as usual and then put in 2x2 lava.

**Comment by Sibei46** [comment]
我是的是“好吧”

**Comment by Sibei46** [comment]
Confirm that it has been fixed after updating

![Image](https://github.com/user-attachments/assets/79a7aaf4-2e17-4636-97d2-76590d453ffb)

**Comment by inexcode** [comment]
> Confirm that it has been fixed after updating

After updating to which version? Lava is still broken on NeOculus 1.8.5...

**Comment by Lonmo0208** [comment]
> > 确认更新后已修复
> 
> 更新到哪个版本后？熔岩在 NeOculus 1.8.5 上仍然被破坏......

因为是伪修复 在1.8.4，作者为了兼容一些老光影，导致很多光影出现了其他错误，你仔细看看你截图里的光影的水面还有植物的摇晃，你可以对比1.8.3或1.8.5的水面和植物摇晃

**Comment by Lonmo0208** [comment]
> > 确认更新后已修复
> 
> 更新到哪个版本后？熔岩在 NeOculus 1.8.5 上仍然被破坏......

已提交修复，等下个版本更新，或等合并后，自行下载最新构建版

**Comment by inexcode** [comment]
Версия 1.8.6, лава всё ещё слишком яркая...

![Image](https://github.com/user-attachments/assets/11a7a1f4-3874-401f-8b52-4c2d3e47e90d)
